[logger]
# Level of logging: 'info' or 'debug'. This helps track its behavior and identity issues
level = "info"

[client]
# Whether to enable st.experimental_getqueryparams.
# By disabling query strings, sensitive information cannot be passed through the URL
enableQueryString = false

# If false, will attempt to open a browser window on start.
headless = false

# Port where app is served.
port = 8501

# By disabling support for Cross-Origin Request Sharing (CORS) protection, this limits the app's exposure
# to potential external threats.
enableCORS = false

# If false, prevents Streamlit from automatically rerunning script when file changes.
runOnSave = true

# Setting the theme to the interface
[theme]
base = "light"
primaryColor = "#E694FF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#FFFFE0"
font = "sans-serif"


[browser]
# Compliance to not gather and store usage statistics
gatherUsageStats = false
